language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

  # PyPy versions
  - "pypy"
  #- "pypy-5.3.1"
# command to install dependencies
install:
  - pip install -r requirements.txt
#  - pip install scipy

# command to run tests
#script: pytest
